{{- if .Values.deploymentConfig }}
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ include "quarkus-token-handler.fullname" . }}
  labels:
    {{- include "quarkus-token-handler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas.min }}
  revisionHistoryLimit: 10
  selector:
    {{- include "quarkus-token-handler.selectorLabels" . | nindent 4 }}
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/q/metrics'
        prometheus.io/port: '8080'
        rollme: {{ randAlphaNum 5 | quote }}
      creationTimestamp: null
      labels:
        {{- include "quarkus-token-handler.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - env:
            - name: QUARKUS_PROFILE
              value: prod
            - name: QUARKUS_LOG_LEVEL
              value: INFO
            - name: QUARKUS_HTTP_CORS_ORIGINS
              value: {{ .Values.frontend.url | quote }}
            - name: KEYCLOAK_URL
              valueFrom:
                secretKeyRef:
                  key: keycloak-url
                  name: {{ include "quarkus-token-handler.fullname" . }}
            - name: KEYCLOAK_REAM
              valueFrom:
                secretKeyRef:
                  key: keycloak-realm
                  name: {{ include "quarkus-token-handler.fullname" . }}
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: keycloak-clientId
                  name: {{ include "quarkus-token-handler.fullname" . }}
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: keycloak-clientSecret
                  name: {{ include "quarkus-token-handler.fullname" . }}
            - name: TRUSTED_WEB_ORIGINS
              valueFrom:
                secretKeyRef:
                  key: trustedWebOrigins
                  name: {{ include "quarkus-token-handler.fullname" . }}
            - name: REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  key: redirectUri
                  name: {{ include "quarkus-token-handler.fullname" . }}
            - name: COOKIE_NAME_PREFIX
              valueFrom:
                secretKeyRef:
                  key: cookieNamePrefix
                  name: {{ include "quarkus-token-handler.fullname" . }}
            - name: COOKIE_EXPIRES_SEC
              valueFrom:
                secretKeyRef:
                  key: cookieExpiresSec
                  name: {{ include "quarkus-token-handler.fullname" . }}
            - name: COOKIE_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  key: encKey
                  name: {{ include "quarkus-token-handler.fullname" . }}
            - name: COOKIE_ENCRYPTION_SALT
              valueFrom:
                secretKeyRef:
                  key: salt
                  name: {{ include "quarkus-token-handler.fullname" . }}
            - name: COOKIE_ENCYPTION_IV
              valueFrom:
                secretKeyRef:
                  key: ivKey
                  name: {{ include "quarkus-token-handler.fullname" . }}
          image: ''
          imagePullPolicy: Always
          name: {{ include "quarkus-token-handler.name" . }}
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          resources:
            limits:
              cpu: '600m'
              memory: 500Mi
            requests:
              cpu: '100m'
              memory: 50Mi
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - {{ include "quarkus-token-handler.name" . }}
        from:
          kind: ImageStreamTag
          name: {{ include "quarkus-token-handler.fullname" . }}:{{ .Values.image_version }}
        lastTriggeredImage: ""
      type: ImageChange
{{- end }}
