---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "quarkus-token-handler.fullname" . }}
  labels:
    {{- include "quarkus-token-handler.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      deploymentconfig: {{ include "quarkus-token-handler.fullname" . }}
