---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quarkus-token-handler.fullname" . }}
  labels:
    {{- include "quarkus-token-handler.labels" . | nindent 4 }}
stringData:
  keycloak-url: {{ .Values.keycloak.url | quote }}
  keycloak-realm: {{ .Values.keycloak.realm | quote }}
  keycloak-clientId: {{ .Values.keycloak.clientId | quote }}
  keycloak-clientSecret: {{ .Values.keycloak.clientSecret | quote }}
  trustStorePwd: {{ .Values.trustStorePwd | quote }}
  trustedWebOrigins: {{ .Values.trustedWebOrigins | quote }}
  redirectUri: {{ .Values.redirectUri | quote }}
  cookieNamePrefix: {{ .Values.cookieNamePrefix | quote }}
  cookieExpiresSec: {{ .Values.cookieExpiresSec | quote }}
  cookieDomain: {{ .Values.cookieDomain | quote }}
  encKey: {{ .Values.encKey | quote }}
  salt: {{ .Values.salt | quote }}
  ivKey: {{ .Values.ivKey | quote }}
  java-options: {{ .Values.javaOptions | quote }}
