---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quarkus-token-handler.fullname" . }}
  labels:
    {{- include "quarkus-token-handler.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: tcp-8080
    - port: 8443
      protocol: TCP
      targetPort: 8443
      name: tcp-8443
    - port: 5005
      protocol: TCP
      targetPort: 5005
      name: tcp-5005
  selector:
    {{- include "quarkus-token-handler.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
