version: '3'
services:

  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    ports:
      - "8443:8443"
      - "8787:8787"
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      X509_CA_BUNDLE: "/var/run/secrets/example.ca.pem"
      KEYCLOAK_LOGLEVEL: DEBUG
      DEBUG: 'true'
      DEBUG_PORT: '*:8787'
    volumes:
      - ./example.ca.pem:/var/run/secrets/example.ca.pem:Z
