{{- if (eq .Values.route true) }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "quarkus-token-handler-front-end.fullname" . }}
  labels:
    {{- include "quarkus-token-handler-front-end.labels" . | nindent 4 }}
spec:
  port:
    targetPort: tcp-8443
  to:
    kind: Service
    name: {{ include "quarkus-token-handler-front-end.fullname" . }}
    weight: 100
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - status: 'True'
          type: Admitted
{{ end }}
