---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quarkus-token-handler-api.fullname" . }}
  labels:
    {{- include "quarkus-token-handler-api.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: tcp-8080
  selector:
    {{- include "quarkus-token-handler-api.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
