---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quarkus-token-handler-proxy.fullname" . }}
  labels:
    {{- include "quarkus-token-handler-proxy.labels" . | nindent 4 }}
stringData:
  encKey: {{ .Values.encKey | quote }}
  salt: {{ .Values.salt | quote }}
  ivKey: {{ .Values.ivKey | quote }}
  cookieNamePrefix: {{ .Values.cookieNamePrefix | quote }}
